import type { Metadata } from "next";
import { Geist, Geist_Mono, Asul } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const asul = Asul({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-asul",
  display: "swap",
  style: "normal",
  preload: true,
  fallback: ["system-ui", "sans-serif"],

});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TOdo List App App",
  description: "Generated by create next app with TypeScript and Tailwind CSS",
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon-32x32.png",
  },
  themeColor: "#000000",
  openGraph: {
    title: "TOdo List App App",
    description: "Generated by create next app with TypeScript and Tailwind CSS",
    url: "https://yourdomain.com",
    siteName: "TOdo List App",
    images: [
      {
        url: "https://yourdomain.com/og-image.png",
        width: 1200,
        height: 630,
        alt: "TOdo List App Open Graph Image",
      },
    ],
    locale: "pt-BR",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
